define({emp:{fileMapping:{Delete:"",New:"",TargetOA:"",MappingModification:"",SourceOFNIRF:"",MobileFMS:"",PleaseSelec:"",Query:"",YouAITPOD:"",TheATIRF:"",TargetOFIRF:"",DeletingSucceeded:"",InvoiceIEW:"",SourceOFN:"",TargetOAIIRF:"",RepaymentRecord:"",TargetObjectField:"",AreYSTDTITA:"",ProjectConditions:"",InvoiceDM:"",Determine:"",SourceOAIIRF:"",ContentHNBM:"",Reset:"",EnableToInput:"",AddMS:"",MobilePWTM:"",TypeOfAssociation:"",NoDUTS:"",Modify:"",SourceOAI:"",DuplicateDAE:"",InvoiceInformation:"",SourceObjectName:"",Type:"",TargetOAI:"",Canale:"",BorrowingC:"",Save:"",Prompt:"",MappingAddition:"",SourceOA:""}}})

define({emp:{fileMapping:{Delete:"删除",New:"新增",TargetOA:"目标对象关联",MappingModification:"映射修改",SourceOFNIRF:"源对象字段名是必填项",MobileFMS:"移动字段映射设置",PleaseSelec:"请选择",Query:"查询",YouAITPOD:"您正在进行删除操作",TheATIRF:"关联类型是必填项",TargetOFIRF:"目标对象字段是必填项",DeletingSucceeded:"删除成功！",InvoiceIEW:"发票信息.易道",SourceOFN:"源对象字段名",TargetOAIIRF:"目标对象关联id是必填项",RepaymentRecord:"还款记录",TargetObjectField:"目标对象字段",AreYSTDTITA:"您确定要删除这发票类型为",ProjectConditions:"项目条件",InvoiceDM:"发票单据映射",Determine:"确定",SourceOAIIRF:"源对象关联id是必填项",ContentHNBM:"内容未修改",Reset:"重置",EnableToInput:"允许输入",AddMS:"新增/修改成功！",MobilePWTM:"移动PC宽表映射",TypeOfAssociation:"关联类型",NoDUTS:"暂无数据,无法保存",Modify:"修改",SourceOAI:"源对象关联id",DuplicateDAE:"已存在重复数据",InvoiceInformation:"发票信息.fpxx",SourceObjectName:"源对象名",Type:"类型",TargetOAI:"目标对象关联id",Canale:"取消",BorrowingC:"借款核销",Save:"保存",Prompt:"提示",MappingAddition:"的数据么？",SourceOA:"源对象关联"}}})


define({emp:{baseCostType:{New:"新增",Category:"类别",Query:"查询",Cancel:"取消",AddCategory:"添加类别",DeletingSucceeded:"删除成功！",YouAreDeleting:"您正在进行删除操作",NewCategory:"新增类别",Remarks:"备注：",CategoryAddition:"类别添加",TheTypeOfID:"类型GID：",EnterKASA:"输入关键字，自动搜索",Determine:"确定",Reset:"重置",SuccessfullyAdded:"新增成功！",ChineseNOC:"类别中文名：",CategoryID:"类别ID",ModifiedS:"修改成功。",Modify:"修改",ModificationType:"修改类型",AreYSYWTDTGATD:"您确定要删除这GID为的数据么？",IconAOC:"类别图标地址：",Save:"保存",Prompt:"提示",TheTOIAEOIEPMI:"类型ID已存在或为空请修改。"}}})



define({emp:{baseCostType:{New:"",Category:"",Query:"",Cancel:"",AddCategory:"",DeletingSucceeded:"",YouAreDeleting:"",NewCategory:"",Remarks:"",CategoryAddition:"",TheTypeOfID:"",EnterKASA:"",Determine:"",Reset:"",SuccessfullyAdded:"",ChineseNOC:"",CategoryID:"",ModifiedS:"",Modify:"",ModificationType:"",AreYSYWTDTGATD:"",IconAOC:"",Save:"",Prompt:"",TheTOIAEOIEPMI:""}}})


define({emp:{baseBillType:{Delete:"",IconAddress:"",New:"",TheMNOAM1CTBE:"",PCCDID:"",Cancel:"",ApplicableUnit:"",PleaseETMN:"",Process:"",Edit:"",Document:"",Deactivate:"",DeleteConfirmation:"",OperationSuccessful:"",PullGF:"",NoProcessAvailable:"",MobileRDC:"",Modify:"",Scene:"",NoSceneAvailable:"",MenuName:"",NotSPGF:"",NotUPGF:"",PleaseSAP:"",Published:"",PCMLEN:"",PleaseSTD:"",Save:"",Close:"",TheIAOAM4CTBE:""}}})
define({emp:{baseBillType:{Delete:"删除",IconAddress:"图标地址",New:"新增",TheMNOAM1CTBE:"菜单名称最大只允许输入100个字符。",PCCDID:"PC端菜单ID",Cancel:"取消",ApplicableUnit:"适用单位",PleaseETMN:"请输入菜单名称。",Process:"流程",Edit:"编辑",Document:"单据",Deactivate:"停用",DeleteConfirmation:"删除确认",OperationSuccessful:"操作成功",PullGF:"拉生成功能",NoProcessAvailable:"无可用流程",MobileRDC:"移动报销单据配置",Modify:"修改",Scene:"场景",NoSceneAvailable:"无可用场景",MenuName:"菜单名称",NotSPGF:"未指定拉生成功能",NotUPGF:"无可用拉生成功能",PleaseSAP:"请选择流程。",Published:"已发布",PCMLEN:"PC端菜单ID最大只允许输入50个字符",PleaseSTD:"请选择单据。",Save:"保存",Close:"关闭",TheIAOAM4CTBE:"图标地址最大只允许输入400个字符。"}}}	)